version: "3.7"

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    command: mongod --quiet --logpath /dev/null
    volumes:
      - mongodata:/data/db

  localstack:
    image: localstack/localstack
    container_name: localstack_service
    ports:
      - 4566:4566
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=ap-southeast-1
      - DEBUG=2
      - PERSISTENCE=1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  mongodata: {}
