version: "3.7"

services:
  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=ap-southeast-1
      - DEBUG=2
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"